#!/usr/bin/python3

import os
import sys
import wetsuite.helpers.localdata
import wetsuite.helpers.format


def main():
    ' see module docstring '

    for fn in sys.argv[1:]:
        fn = os.path.abspath(fn)

        with wetsuite.helpers.localdata.LocalKV( fn,  None,None ) as kv:
            print("== %s =="%fn)
            item = kv.summary(get_num_items=True)

            bytesize = item.pop('size_bytes')
            num_items = item.pop('num_items', None)

            print('  %5sB'%wetsuite.helpers.format.kmgtp(bytesize, extradigits=0), end='')

            print('  %8s '%item.get('valtype',''), end='')

            if num_items is not None:
                print('   %9s items     %5sB/item'%(
                    wetsuite.helpers.format.kmgtp(num_items,                 extradigits=0),
                    wetsuite.helpers.format.kmgtp(item.pop('avgsize_bytes'), extradigits=0)
                    ), end='')

            #description = item.pop('description', None)
            #if description is not None:
            #    print('description: %sB'%( '\n'.join(textwrap.wrap(description, 90, subsequent_indent='             '))))

            #print('       %s'%item.pop('path'), end='')

            print()

if __name__ == '__main__':
    main()
